### ISSUE TITLE
Adding animation

### ISSUE THREAD

**Issue by Leocardoso94** [Leocardoso94/beauty-stars#5]
Adding some nice animation when star rating change

**Comment by ploh007** [comment]
I'd like to give this a shot! Can this be assigned to me?

**Comment by Leocardoso94** [comment]
Of course. Go ahead 🚀

**Comment by ploh007** [comment]
All done. Let me know if this was the desired outcome. 😄

**Comment by Leocardoso94** [comment]
Good job! Thanks for your contribution @ploh007

**Comment by ploh007** [comment]
My pleasure @Leocardoso94!
